### PR TITLE
Update firebase dependency

### PR DESCRIPTION
**Pull request by samtstern**
Updates Firebase to the latest version. I don't think geofire has a history of doing breaking changes when we adopt a breaking underlying Firebase SDK but I am open to it.

### CODE REVIEW

**Comment by ziyaddin** [comment]
`Reference` type incompatibility between Firebase and GeoFire has been around for a long time.

**Comment by samtstern** [comment]
> `Reference` type incompatibility between Firebase and GeoFire has been around for a long time.

Interesting what do you do to get around it?

**Comment by ziyaddin** [comment]
> Interesting what do you do to get around it?

I have come up with this workaround:

```ts
import { database } from 'firebase-admin';  // or 'firebase' package
import { GeoFire } from 'geofire';
import DatabaseTypes from '@firebase/database-types';

const firebaseRef = database().ref();
const geofire = new GeoFire((firebaseRef as unknown) as DatabaseTypes.Reference)
```

I transform the `Reference` type of `firebase-admin` package (or `firebase` package) to `unknown` type and then to `Reference` type of `@firebase/database-types`.

**Comment by samtstern** [comment]
@ziyaddin thanks for sharing, that sounds like what I would do as well.  The good news is that after this PR you should no longer have that conflict on the latest SDK.

**Comment by ziyaddin** [comment]
Great, thanks for fixing it.

**Review by puf — APPROVED** [review]
LGTM. Thanks for fixing this.

**Comment by samtstern** [comment]
@puf please make sure to squash and merge in the future, all of my commits for this PR hit `master` and there was a lot of guess and check.

**Pull request merged**
