### PR TITLE
Remove RSVP in favour of native Promise

### PR DESCRIPTION
**Pull request by rolandjitsu**
I was not able to test this as some of the npm deps could not be install, but I am sure that everything should be running properly.

Also, some of the npm packages are deprecated (`gulp-karma`), it may be a good idea to update the dev deps and the gulp tasks.

It might also be a good idea to start using ES6 and use a simple transpile to ES5 task for creating dist packages.

Implements https://github.com/firebase/geofire-js/issues/84.

### CODE REVIEW

**Comment by rolandjitsu** [comment]
I signed it!

**Comment by jwngr** [comment]
Thanks @rolandjitsu! This is awesome. Apologies on not having time to look at this just now. I plan to get to it in the near future though.

> Also, some of the npm packages are deprecated (gulp-karma), it may be a good idea to update the dev deps and the gulp tasks.

I am aware of the out-of-date deps. The JS tooling community moves fast, which is both awesome and a bit daunting. I have a TODO to update all the deps and get the tests running once again. I'll do that before merging your change in.

> It might also be a good idea to start using ES6 and use a simple transpile to ES5 task for creating dist packages.

Yeah this would be a good addition. This library was made before ES6 was the new hotness and the tooling wasn't as good back when I made this. I'll look into this time permitting.

**Comment by rolandjitsu** [comment]
It looks like JOB [2](https://travis-ci.org/firebase/geofire-js/jobs/108097930) always fails, but JOB [1](https://travis-ci.org/firebase/geofire-js/jobs/108097929) passes.

**Comment by rolandjitsu** [comment]
@jwngr If you'd like, I'd be opened to do a little facelift to this lib (update the deps, use ES6, etc.). Unless you already have some ongoing work on it.

I plan on using this library and Firebase extensively on one of my projects, so I think it would be time well spent on developing on this lib.

As for merging the pull request, I do hope that you will have time within this week to do it, as I cannot use it until RSVP is gone from it.

**Comment by jwngr** [comment]
Feel free to take a crack at updating things. I'm more interested in updating the deps at present rather than using ES6 just yet, but if you can make it work in a backwards-compatible manner, go ahead. And yeah, I plan to look at before the end of this week!

**Comment by jwngr** [comment]
Note that I do actually have a branch which is still not working fully but has started to update dependencies: https://github.com/firebase/geofire-js/tree/jw-update-deps

**Comment by rolandjitsu** [comment]
Great, then I will just try to update the deps and leave the to ES6 update for later. I will take a look at the branch and see if I can start from there.

And maybe at some point, when you think it would be best, I could try to do the update to ES6.

**Comment by jwngr** [comment]
Thanks again for the PR and sorry for the slow turnaround.

I'm closing this in favor of https://github.com/firebase/geofire-js/pull/93 which gets rid of the RSVP dependency entirely by just using the promise API built into Firebase `2.4.0` and higher. Once that gets merged in, I'll cut a `4.0.0` release for GeoFire and you can remove RSVP from your app!

**Comment by rolandjitsu** [comment]
@jwngr sounds great :+1: Looking forward to it.

**Comment by jwngr** [comment]
[GeoFire `4.0.0`](https://github.com/firebase/geofire-js/releases/tag/v4.0.0) has been released! Enjoy!

**Pull request closed without merging**
