### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jacob-israel-turner**

### CODE REVIEW

**Comment by jacob-israel-turner** [comment]
I signed it!

**Comment by jwngr** [comment]
Tests failed but it's obviously not your fault. I opened https://github.com/firebase/geofire-js/issues/68 to track the build failure. I'll hopefully get that fixed in a couple days.

**Comment by jacob-israel-turner** [comment]
No worries. Great library, I'm loving it so far! :)

**Comment by jwngr** [comment]
Glad you are enjoying it. Hopefully you don't come across any other typos or bugs :)

**Pull request merged**
